--ozone-platform=wayland
--ozone-platform-hint=wayland
--use-gl=egl
--enable-features=TouchpadOverscrollHistoryNavigation,VaapiVideoDecodeLinuxGL,VaapiVideoEncoder
--enable-gpu-rasterization
--enable-zero-copy